version: "3.9"

services:
  db:
    image: postgres:17
    container_name: alquimia_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alquimia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: alquimia_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: alquimia_backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alquimia
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["./alquimia-backend"]

  worker:
    build:
      context: ./backend
    container_name: alquimia_worker
    command: ["./worker"]
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alquimia
    restart: always

  frontend:
    build: ./frontend
    container_name: alquimia_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
